//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        public int Id { get; set; }
        public int IdCourse { get; set; }
        public string NameOfTheLesson { get; set; }
        public string LinkVideo { get; set; }
        public string LessonContent { get; set; }
        public string LinkDrive { get; set; }
        public bool Status { get; set; }
        public Nullable<int> IndexNumber { get; set; }
    }
}
