//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public bool ISATEACHER { get; set; }
        public bool STATUS { get; set; }
    }
}
